<a href="https://colab.research.google.com/github/arshiafreen090/Numpy_/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# np.array
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
# 1D,2D and 3D array
import numpy as np

arr_1D= np.array([1, 2, 3, 4, 5])
arr_2D= np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_3D= np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("1D array:")
print(arr_1D)
print()
print("2D array:")
print(arr_2D)
print()
print("3D array:")
print(arr_3D)
print()

1D array:
[1 2 3 4 5]

2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

3D array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

