<a href="https://colab.research.google.com/github/arshiafreen090/Numpy_/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##What is numpy?
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

##Numpy Arrays Vs Python Sequences
* NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

* The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

* NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

* A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.




## Creating Numpy Arrays


In [ ]:
# np.array
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
import numpy as np

arr_1D = np.array([1, 2, 3, 4, 5])
arr_2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(f"""1D array:
{arr_1D}

2D array:
{arr_2D}

3D array:
{arr_3D}
""")

1D array:
[1 2 3 4 5]

2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

3D array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]



In [ ]:
# Zeros, ones and full
import numpy as np

a = np.zeros((3,4))
b = np.ones((2,3,4))
c = np.full((2,2,2), 7)

print(a, "\n\n", b, "\n\n", c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]] 

 [[[7 7]
  [7 7]]

 [[7 7]
  [7 7]]]


In [ ]:
# creating sequences of numbers in numpy
import numpy as np

arr= np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [ ]:
# identity matrix
import numpy as np

i= np.identity(3) # can use np.eye(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# np.linspace
import numpy as np
a= np.linspace(-10,10,10,dtype=int)
print(a)

[-10  -8  -6  -4  -2   1   3   5   7  10]


In [ ]:
# with reshape
import numpy as np

a= np.arange(16).reshape(2,2,2,2)
print(a)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


In [ ]:
# np.random
import numpy as np
import random
r= np.random.random((3,4))
print(r)

[[0.6105183  0.86751954 0.67876363 0.45877165]
 [0.95045942 0.38066601 0.69854824 0.86260168]
 [0.62447878 0.5627439  0.95701226 0.91933424]]


## Array Properties and Operations

In [ ]:
# np.shape
import numpy as np

a= np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [ ]:
# np.size
import numpy as np

a= np.array([[1,2,3],[4,5,6]])
print(a)
print()
print("Total elements in matrix/array: ", a.size)

[[1 2 3]
 [4 5 6]]

Total elements in matrix/array:  6


In [ ]:
# np.ndim
import numpy as np

a= np.array([[[1,2,3],[4,5,6],
              [2,5,6],[7,3,1]]])
print(a.ndim)

3


In [ ]:
# np.dtype
import numpy as np

a= np.array([[1.9,2.5,3],[4,5.0,6]])
print(a.dtype)

float64


In [ ]:
# np.astype
import numpy as np

a= np.array([[1,2,3],[4,5,6]])
print(a.dtype)
print()
p=a.astype(float)
print(p.dtype)
print(p)

int64

float64
[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
# numpy oprations
# arthimatic(+,-,*,/,**)
import numpy as np

a= np.array([[1,2,3],[4,5,6]])
b= np.array([[7,8,9],[10,11,12]])
print(f'{a+b}\n\n{a+3}\n\n{a-b}\n\n{a*b}\n\n{a/b}\n\n{a**2}')

# relational(==,!=,<,>,<=,>=)
print(f'\n{a==b}\n\n{a!=b}\n\n{a<b}\n\n{a>b}\n\n{a<=b}\n\n{a>=b}')



[[ 8 10 12]
 [14 16 18]]

[[4 5 6]
 [7 8 9]]

[[-6 -6 -6]
 [-6 -6 -6]]

[[ 7 16 27]
 [40 55 72]]

[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]

[[ 1  4  9]
 [16 25 36]]

[[False False False]
 [False False False]]

[[ True  True  True]
 [ True  True  True]]

[[ True  True  True]
 [ True  True  True]]

[[False False False]
 [False False False]]

[[ True  True  True]
 [ True  True  True]]

[[False False False]
 [False False False]]


##Functions

In [ ]:
#Aggreation Fuction
import numpy as np

arr= ([10,9,34,65,34,23])

print("The min No.: ",np.min(arr))
print("The max No.:",np.max(arr))
print("The Sum:",np.sum(arr))
print("The Mean:",np.mean(arr))
print("The Median:",np.median(arr))
print("The Standard deviation:",np.std(arr))
print("The Variance:",np.var(arr))

The min No.:  9
The max No.: 65
The Sum: 175
The Mean: 29.166666666666668
The Median: 28.5
The Standard deviation: 18.898118660038328
The Variance: 357.1388888888889


In [ ]:
# trigonomoetric functions
import numpy as np

a1= np.array([0,30,45,60,90])
print(np.sin(a1*np.pi/180))
print(np.cos(a1*np.pi/180))
print(np.tan(a1*np.pi/180))

[0.         0.5        0.70710678 0.8660254  1.        ]
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [ ]:
# round/floor/ceil
import numpy as np

print(np.floor(np.random.random((2,3))*100))
print(np.ceil(np.random.random((2,3))*100))

[[36. 10. 28.]
 [31.  0. 79.]]
[[11. 89. 13.]
 [83. 30. 22.]]


In [ ]:
# dot product
import numpy as np

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

print(np.dot(a2,a3))

[[114 120 126]
 [378 400 422]
 [642 680 718]]


## Indexing and slicing

In [3]:
# indexing
import numpy as np

arr= np.array([10,20,30,40,50,60,70])

print(arr[1:5])
print(arr[:5])
print(arr[::2])
print(arr[::-1])


[20 30 40 50]
[10 20 30 40 50]
[10 30 50 70]
[70 60 50 40 30 20 10]


In [4]:
# fancy indexing
import numpy as np

arr= np.array([13,5,6,3,56,3,2,54])
print (arr[[0,2,4]])  #used to extract multiple elements from array also it make copy from the og.


[13  6 56]


In [5]:
# filtering (boolean masking)
import numpy as np

arr= np.array([13,5,6,3,56,3,2,54])
print(arr[arr>10])

[13 56 54]


In [11]:
# reshaping and manipulation
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
# reshaped_arr = arr.reshape(2,3)
# print(reshaped_arr)
reshaped_arr1 = arr.reshape(2,2,3) #it only create a POV not copy
print(reshaped_arr1)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [12]:
'''
.ravel() ----> view
.flatten ----> copy
'''
import numpy as np

arr_2d= np.array([[1,2,3], [4,5,6]])
print(arr_2d.ravel())
print(arr_2d.flatten())

[1 2 3 4 5 6]
[1 2 3 4 5 6]


## Array Modification

In [17]:
# insert
import numpy as np

arr_1d= np.array([1,2,3,4,5,6,7,8,9])
print(arr_1d)
new_arr_1d= np.insert(arr_1d, 2, 100)          #1D
print("New 1d array",new_arr_1d)
print()
arr_2d= np.array([[1,2],[3,5]])
print(arr_2d)
new_arr_2d= np.insert(arr_2d,1,[5,6], axis=0)   #2D
print("New 2d array",new_arr_2d)

[1 2 3 4 5 6 7 8 9]
New 1d array [  1   2 100   3   4   5   6   7   8   9]
[[1 2]
 [3 5]]
New 2d array [[1 2]
 [5 6]
 [3 5]]


In [1]:
# append
import numpy as np

arr= np.array([1,2,3,4,5])
print(arr)
new_arr= np.append(arr, [6,7,8])
print(new_arr)

[1 2 3 4 5]
[1 2 3 4 5 6 7 8]


In [3]:
# concatenation
import numpy as np

arr1= np.array([1,2,3,4])
arr2= np.array([5,6,7,8])

print(np.concatenate((arr1,arr2)))

# use of axis
arr1= np.array([[1,2],[3,4]])
arr2= np.array([[5,6],[7,8]])

print(np.concatenate((arr1,arr2), axis=1)) #axis =0 ---> vertical stacking
                                           #axis =1 ---> horizental stacking


[1 2 3 4 5 6 7 8]
[[1 2 5 6]
 [3 4 7 8]]


In [7]:
# delete
import numpy as np
arr= np.array([[1,2,4],[5,6,7]])
print(np.delete(arr,1,axis=1))
print(np.delete(arr,1,axis=0))

[[1 4]
 [5 7]]
[[1 2 4]]


In [8]:
# stacking
import numpy as np

arr1= np.array([1,2,3])
arr2= np.array([4,5,6])

print(np.stack((arr1,arr2)))
print(np.hstack((arr1,arr2)))
print(np.vstack((arr1,arr2)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [10]:
# spiliting
import numpy as np
arr= np.array([1,2,3,4,5,6])
new_arr= np.split(arr,2)
print(new_arr)

[array([1, 2, 3]), array([4, 5, 6])]


## Broadcasting and vectorization

Broadcasting = "Make different shapes work together"
, So broadcasting is about aligning different shapes so an operation can be performed.

Vectorization = "Do the operation on the whole array"
, Vectorization means performing an operation on an entire array at once instead of explicitly looping through individual elements.

In [13]:
# Case 1: Same shape

import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
print(a+b)

'''
(2, 3)
(2, 3)
Compatible'''

# Case 2: Different shape

a=np.array([[1,2,3],[4,5,6]])
b=np.array([7,8,9])
print(a+b)

'''
(2, 3)
(1, 3)
3 = 3, 2 vs 1
compatible
'''

# case 3: One array has fewer dimensions
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([10, 20, 30])
print(A+B)
'''
A → (2, 3)
B → (3,)
NumPy adds a missing dimension to the left.
B → (1,3)
compatible
'''
# case 4: differnt dimention i.e not compatible

# A = np.array([
#     [1, 2, 3, 4],
#     [5, 6, 7, 8],
#     [9, 10, 11, 12]
# ])

# B = np.array([10, 20])
# print(A+B)
'''
(3, 4)
(2,)
4 vs 2
i.e not compatible
'''


[[ 8 10 12]
 [14 16 18]]
[[ 8 10 12]
 [11 13 15]]
[[11 22 33]
 [14 25 36]]


'\n(3, 4)\n(2,)\n4 vs 2\ni.e not compatible\n'

In [14]:
# vectorzation
import numpy as np
arr= np.array([1,2,3,4,5,6])
new_arr= arr*10
print(new_arr)

[10 20 30 40 50 60]


## Handling Missing Value

In [15]:
# isnan
import numpy as np

arr= np.array([1,2,np.nan,4,5,6,np.nan])
print(np.isnan(arr))

#replacing the isnan
cleaned_arr= np.nan_to_num(arr,nan=100)
print(cleaned_arr)

# infitne
arr_inf= np.array([1,2,3,np.inf,4,5,np.inf])
print(np.isinf(arr_inf))

# replacing the isinf
cleaned_arr_inf= np.nan_to_num(arr_inf, posinf=1000, neginf=-1000)
print(cleaned_arr_inf)


[False False  True False False False  True]
[  1.   2. 100.   4.   5.   6. 100.]
[False False False  True False False  True]
[   1.    2.    3. 1000.    4.    5. 1000.]
